In [ ]:
# 반복문 한번 n
# 반복문 두번 n*n
# 반복문 세번 n*n*n --> 거의 코테 사용X
for x in range(100):
    for y in range(100):
        for z in range(100):
            pass

In [ ]:
def fibonacci_recursive(n: int) -> int:
    """
    n번째 피보나치 수를 재귀적으로 계산하여 반환합니다.
    (F(0)=0, F(1)=1 기준)

    주의: 이 순수 재귀 방식은 n이 커질수록 동일한 계산을 반복하여
          매우 비효율적입니다 (시간 복잡도 O(2^n)).
          실제 사용 시에는 메모이제이션(동적 프로그래밍)을 사용한 최적화가 필요합니다.
    """
    if not isinstance(n, int) or n < 0:
        raise ValueError("입력값은 0 이상의 정수여야 합니다.")  # 일부로 에러를 일으키는 raise
    if n <= 1:  # 기본 조건: F(0) = 0, F(1) = 1
        return n
    else:
        # F(n) = F(n-1) + F(n-2)
        return fibonacci_recursive(n - 1) + fibonacci_recursive(n - 2)

In [3]:
help(fibonacci_recursive)

Help on function fibonacci_recursive in module __main__:

fibonacci_recursive(n: int) -> int
    n번째 피보나치 수를 재귀적으로 계산하여 반환합니다.
    (F(0)=0, F(1)=1 기준)
    
    주의: 이 순수 재귀 방식은 n이 커질수록 동일한 계산을 반복하여
          매우 비효율적입니다 (시간 복잡도 O(2^n)).
          실제 사용 시에는 메모이제이션(동적 프로그래밍)을 사용한 최적화가 필요합니다.



In [ ]:
fibonacci_recursive("a")

In [ ]:
import numpy as np #분석이나 AI 파이썬 활용하게 해줌줌

In [8]:
np.array([1,2,3,4,5]) * 2

array([ 2,  4,  6,  8, 10])

In [9]:
np.arange(20).ndim

1

In [10]:
np.arange(20).shape

(20,)

In [ ]:
np.arange(20).reshape(4,5) # 행,열

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
np.arange(20).reshape(-1,4,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [13]:
# 컬러(RGB) 사진은 3차원 흑백은 2차원

In [14]:
np.arange(20).reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [15]:
np.arange(20).reshape(5,4)
np.arange(20).reshape(-1,4) # 뒤에 4가 있으면 결국 5밖에 들어가지 못한다.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
a = [10, 20, 30, 40, 50, 60, 70, 80]
sum(a)/len(a) #평균

45.0

In [ ]:
np.mean(a) # 평균

np.float64(45.0)

In [ ]:
# 분산
np.var(a)

np.float64(525.0)

In [ ]:
# 표준편차
np.std(a)

np.float64(22.9128784747792)

In [20]:
import zipfile

In [23]:
with zipfile.ZipFile("./이름_생년_성별_10000.zip") as f:
    f.extractall("./name")

In [24]:
import os, shutil, pathlib

In [ ]:
f = open("./myfilelist.txt", "w", encoding='utf-8')
for roots, dirs, files in os.walk("c:/windows/"):
    for file in files:
        print(f"{roots}{file}")
f.close()

In [29]:
# os.mkdir("./customer/male") # customer 경로까지 없으면 에러
pathlib.Path("./customer/male").mkdir(parents=True, exist_ok=True)
pathlib.Path("./customer/female").mkdir(parents=True, exist_ok=True)
male = []
female = []
for file in os.listdir("./name"):
    if file.split("_")[-1][0] in ['1', '3']:
        with open(f"./name/{file}", "r") as f:
            male.append((int(f.read().replace(",", ""))))
        shutil.move(f"./name/{file}", f"./customer/male/{file}")
    elif file.split("_")[-1][0] in ['2', '4']:
        with open(f"./name/{file}", "r") as f:
            female.append((int(f.read().replace(",", ""))))
        shutil.move(f"./name/{file}", f"./customer/female/{file}")
    else:
        print("잘못된 파일입니다.")

In [30]:
np.mean(female)

np.float64(12802368.483323347)

In [31]:
np.mean(male)

np.float64(11900177.712397356)

In [ ]:
# 종목코드, 시작날짜, 종료날짜, 경로를 값을 받아 파일을 저장
# 이 때, 파일명은 코드명code.csv파일로 저장장
import requests
from xml.etree import ElementTree as ET
import os
import pandas as pd

def saveStockInfoToCSV(symbol, startdate, enddate, path='./'):
    url = f"https://m.stock.naver.com/front-api/external/chart/domestic/notice?symbol={symbol}&startTime={startdate}&endTime={enddate}&requestType=0"

    data = requests.get(url).text
    root = ET.fromstring(data)
    #items = root.iter(tag='item')

    total = [{'date' : i.get('date'), 'information' : x.text} for i in root.iter(tag='item') for x in i]

    if not os.path.isdir(f"{path}" ):
        os.mkdir(f"{path}")
    pd.DataFrame(total).to_csv(f"{path}{symbol}.csv", index=False)

saveStockInfoToCSV('012450', '20240101', '20250520')
saveStockInfoToCSV('035720', '20211201', '20230120', './stock/')